In [1]:
import pandas as pd

In [2]:
tweets = pd.read_csv('/content/tweet.csv', names = ['target', 'id', 'date', 'flag', 'user', 'content'], encoding = 'latin-1')

In [14]:
tweets.head(5)

target          id                          date      flag  \
0       0  1467810369  Mon Apr 06 22:19:45 PDT 2009  NO_QUERY   
1       0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY   
2       0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY   
3       0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
4       0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   

              user                                            content  
0  _TheSpecialOne_  @switchfoot http://twitpic.com/2y1zl - Awww, t...  
1    scotthamilton  is upset that he can't update his Facebook by ...  
2         mattycus  @Kenichan I dived many times for the ball. Man...  
3          ElleCTF    my whole body feels itchy and like its on fire   
4           Karoli  @nationwideclass no, it's not behaving at all....

In [15]:
tweets.sample()

target          id                          date      flag  \
1046995       4  1957722017  Fri May 29 01:23:55 PDT 2009  NO_QUERY   

               user                                            content  
1046995  Kittycat01  @ladybug8320 morning!! beautiful isnt it! what...

In [3]:
content = tweets.content

In [19]:
content.head()

0    @switchfoot http://twitpic.com/2y1zl - Awww, t...
1    is upset that he can't update his Facebook by ...
2    @Kenichan I dived many times for the ball. Man...
3      my whole body feels itchy and like its on fire 
4    @nationwideclass no, it's not behaving at all....
Name: content, dtype: object

In [4]:
import re

In [5]:
def removeMentions(string : str) -> str:
  return re.sub(r'@[\w\d]{4,15}', '', string)

In [6]:
def removeHashtags(string : str) -> str:
  return re.sub(r'#[\w\d]+', '', string)

In [7]:
def removeLinks(string : str) -> str:
  return re.sub(r'(https?|www)[\w\d.\\\/:]+', '', string)

In [8]:
def remove(string : str) -> str:
  return removeLinks(removeHashtags(removeMentions(string)))

In [48]:
content

0          @switchfoot http://twitpic.com/2y1zl - Awww, t...
1          is upset that he can't update his Facebook by ...
2          @Kenichan I dived many times for the ball. Man...
3            my whole body feels itchy and like its on fire 
4          @nationwideclass no, it's not behaving at all....
                                 ...                        
1599995    Just woke up. Having no school is the best fee...
1599996    TheWDB.com - Very cool to hear old Walt interv...
1599997    Are you ready for your MoJo Makeover? Ask me f...
1599998    Happy 38th Birthday to my boo of alll time!!! ...
1599999    happy #charitytuesday @theNSPCC @SparksCharity...
Name: content, Length: 1600000, dtype: object

In [10]:
cleanTweets = content.apply(remove)

In [43]:
cleanTweets.to_csv('/content/cleanTweets.csv')

In [44]:
cleanTweets.sample(10)

943408      that's good  20 more minutes to soak in your ...
849596     My overun phone is still going strong  new chu...
750906     Havent checked this out since I signed up  Jud...
1257858                     i loooooooove fro yo with mommy 
402136                 I want the GSM version asap, goddamn 
1540368    Jamba juice 4 lunch! Also just got a membershi...
330413                                 it'll work out &lt;3 
1224379    Going to start the day with a workout and a bi...
22111      Oh! It was raining in china grand prix too.. B...
157022      different...headaches all week...lol...and a ...
Name: content, dtype: object

In [11]:
def removePunctuation(string : str) -> str:
  return re.sub('[.,?:!-]', '', string)

In [52]:
def removeExtraSpace(string : str) -> str:
  return re.sub(r'\s+', ' ', string.strip())

In [53]:
removeExtraSpace('  heljlakdj  dkfjalkd   lkdjfa j       j j')

'heljlakdj dkfjalkd lkdjfa j j j'

In [47]:
cleanTweets

0            - Awww, that's a bummer.  You shoulda got Da...
1          is upset that he can't update his Facebook by ...
2           I dived many times for the ball. Managed to s...
3            my whole body feels itchy and like its on fire 
4           no, it's not behaving at all. i'm mad. why am...
                                 ...                        
1599995    Just woke up. Having no school is the best fee...
1599996    TheWDB.com - Very cool to hear old Walt interv...
1599997    Are you ready for your MoJo Makeover? Ask me f...
1599998    Happy 38th Birthday to my boo of alll time!!! ...
1599999                                           happy     
Name: content, Length: 1600000, dtype: object

In [12]:
cleanTweets = cleanTweets.apply(removePunctuation)

In [61]:
cleanTweets = cleanTweets.apply(removeExtraSpace)

In [62]:
cleanTweets

0          Awww that's a bummer You shoulda got David Car...
1          is upset that he can't update his Facebook by ...
2          I dived many times for the ball Managed to sav...
3             my whole body feels itchy and like its on fire
4          no it's not behaving at all i'm mad why am i h...
                                 ...                        
1599995    Just woke up Having no school is the best feel...
1599996    TheWDBcom Very cool to hear old Walt interview...
1599997    Are you ready for your MoJo Makeover Ask me fo...
1599998    Happy 38th Birthday to my boo of alll time Tup...
1599999                                                happy
Name: content, Length: 1600000, dtype: object

In [63]:
cleanTweets.isnull().sum()

0

In [71]:
cleanTweets[cleanTweets == ''].count()

3391

In [72]:
cleanTweets = cleanTweets[cleanTweets != '']

In [73]:
cleanTweets[cleanTweets == ''].count()


0

In [15]:
cleanTweets = cleanTweets.reset_index()

In [16]:
cleanTweets = cleanTweets.drop('index', axis = 1)

In [79]:
cleanTweets

content
0        Awww that's a bummer You shoulda got David Car...
1        is upset that he can't update his Facebook by ...
2        I dived many times for the ball Managed to sav...
3           my whole body feels itchy and like its on fire
4        no it's not behaving at all i'm mad why am i h...
...                                                    ...
1596604  Just woke up Having no school is the best feel...
1596605  TheWDBcom Very cool to hear old Walt interview...
1596606  Are you ready for your MoJo Makeover Ask me fo...
1596607  Happy 38th Birthday to my boo of alll time Tup...
1596608                                              happy

[1596609 rows x 1 columns]

In [81]:
def lowerAll(string : str) -> str:
  return string.lower()

In [85]:
cleanTweets = cleanTweets.content.apply(lowerAll)

In [86]:
cleanTweets

0          awww that's a bummer you shoulda got david car...
1          is upset that he can't update his facebook by ...
2          i dived many times for the ball managed to sav...
3             my whole body feels itchy and like its on fire
4          no it's not behaving at all i'm mad why am i h...
                                 ...                        
1596604    just woke up having no school is the best feel...
1596605    thewdbcom very cool to hear old walt interview...
1596606    are you ready for your mojo makeover ask me fo...
1596607    happy 38th birthday to my boo of alll time tup...
1596608                                                happy
Name: content, Length: 1596609, dtype: object

In [13]:
wordCount = cleanTweets.str.split().str.len()

In [88]:
wordCount

0          16
1          21
2          17
3          10
4          20
           ..
1596604    11
1596605    10
1596606    11
1596607    12
1596608     1
Name: content, Length: 1596609, dtype: int64

In [14]:
cleanTweets = cleanTweets[wordCount > 1]

In [17]:
cleanTweets

content
0           Awww that's a bummer  You shoulda got David...
1        is upset that he can't update his Facebook by ...
2         I dived many times for the ball Managed to sa...
3          my whole body feels itchy and like its on fire 
4         no it's not behaving at all i'm mad why am i ...
...                                                    ...
1581538   Yeah that does work better than just waiting ...
1581539  Just woke up Having no school is the best feel...
1581540  TheWDBcom  Very cool to hear old Walt intervie...
1581541  Are you ready for your MoJo Makeover Ask me fo...
1581542  Happy 38th Birthday to my boo of alll time Tup...

[1581543 rows x 1 columns]

In [9]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [17]:
data = cleanTweets.content.to_list()[:1000]

In [18]:
len(data)

1000

In [19]:
tokenizer.fit_on_texts([*data])

In [23]:
tokenizer.word_index

{'i': 1,
 'to': 2,
 'the': 3,
 'a': 4,
 'my': 5,
 'and': 6,
 'is': 7,
 'in': 8,
 'it': 9,
 'for': 10,
 'of': 11,
 'me': 12,
 'on': 13,
 'you': 14,
 'have': 15,
 'but': 16,
 'so': 17,
 'not': 18,
 'that': 19,
 "i'm": 20,
 'at': 21,
 'just': 22,
 'be': 23,
 'was': 24,
 'work': 25,
 'this': 26,
 'up': 27,
 'no': 28,
 'with': 29,
 'now': 30,
 'go': 31,
 'get': 32,
 'out': 33,
 'day': 34,
 'back': 35,
 'all': 36,
 'today': 37,
 'like': 38,
 'too': 39,
 'do': 40,
 "it's": 41,
 'going': 42,
 'are': 43,
 'got': 44,
 "don't": 45,
 "can't": 46,
 'am': 47,
 'still': 48,
 'good': 49,
 'want': 50,
 'really': 51,
 'had': 52,
 'time': 53,
 'from': 54,
 'im': 55,
 'about': 56,
 'one': 57,
 'what': 58,
 'quot': 59,
 'its': 60,
 'last': 61,
 'sad': 62,
 'miss': 63,
 'has': 64,
 'sleep': 65,
 'know': 66,
 'home': 67,
 'need': 68,
 'night': 69,
 'will': 70,
 'wish': 71,
 'think': 72,
 'some': 73,
 'we': 74,
 'off': 75,
 '2': 76,
 'when': 77,
 'oh': 78,
 'tomorrow': 79,
 'school': 80,
 'much': 81,
 'why': 

In [20]:
type(tokenizer.word_index)

dict

In [20]:
len(tokenizer.word_index)

3096

In [21]:
max(tokenizer.word_index.values())

3096

In [23]:
min(tokenizer.word_index.values())

1

In [24]:
for sentence in data[:5]:
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])
  print(tokenized_sentence)

[[534, 182, 4, 942, 14, 3055, 44, 1748, 6745, 11, 1749, 34, 2, 40, 9, 532]]
[[7, 522, 19, 115, 46, 649, 190, 661, 127, 2769, 9, 6, 313, 406, 84, 4, 1667, 80, 37, 291, 891]]
[[1, 14738, 288, 350, 10, 3, 1836, 1323, 2, 858, 1149, 3, 466, 31, 33, 11, 10169]]
[[5, 459, 696, 373, 1707, 6, 38, 60, 13, 1324]]
[[28, 41, 18, 6746, 21, 36, 20, 578, 82, 47, 1, 100, 176, 1, 46, 97, 14, 36, 113, 92]]


In [22]:
input = []
for sentence in data:
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

    for i in range(len(tokenized_sentence)-1):
      input.append(tokenized_sentence[:i+2])

In [30]:
input[:20]

[[534, 182],
 [534, 182, 4],
 [534, 182, 4, 942],
 [534, 182, 4, 942, 14],
 [534, 182, 4, 942, 14, 3055],
 [534, 182, 4, 942, 14, 3055, 44],
 [534, 182, 4, 942, 14, 3055, 44, 1748],
 [534, 182, 4, 942, 14, 3055, 44, 1748, 6745],
 [534, 182, 4, 942, 14, 3055, 44, 1748, 6745, 11],
 [534, 182, 4, 942, 14, 3055, 44, 1748, 6745, 11, 1749],
 [534, 182, 4, 942, 14, 3055, 44, 1748, 6745, 11, 1749, 34],
 [534, 182, 4, 942, 14, 3055, 44, 1748, 6745, 11, 1749, 34, 2],
 [534, 182, 4, 942, 14, 3055, 44, 1748, 6745, 11, 1749, 34, 2, 40],
 [534, 182, 4, 942, 14, 3055, 44, 1748, 6745, 11, 1749, 34, 2, 40, 9],
 [534, 182, 4, 942, 14, 3055, 44, 1748, 6745, 11, 1749, 34, 2, 40, 9, 532],
 [7, 522],
 [7, 522, 19],
 [7, 522, 19, 115],
 [7, 522, 19, 115, 46],
 [7, 522, 19, 115, 46, 649]]

In [23]:
max_len = max([len(i) for i in input])

In [24]:
max_len

31

In [25]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
tweetInput = pad_sequences(input, maxlen = max_len, padding = 'pre')

In [34]:
tweetInput[:20]

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
         534,  182],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  534,
         182,    4],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,  534,  182,
           4,  942],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,  534,  182,    4,
         942,   14],
       [   0,    0,    0,   

In [26]:
X = tweetInput[:, :-1]

In [36]:
X

array([[  0,   0,   0, ...,   0,   0, 534],
       [  0,   0,   0, ...,   0, 534, 182],
       [  0,   0,   0, ..., 534, 182,   4],
       ...,
       [  0,   0,   0, ..., 111,  86,   6],
       [  0,   0,   0, ...,  86,   6,  30],
       [  0,   0,   0, ...,   6,  30,  41]], dtype=int32)

In [27]:
Y = tweetInput[:, -1]

In [38]:
Y

array([182,   4, 942, ...,  30,  41,  27], dtype=int32)

In [40]:
X.shape

(12187, 30)

In [39]:
Y.shape

(12187,)

In [28]:
from tensorflow.keras.utils import to_categorical

In [29]:
encodedInput = to_categorical(Y, num_classes=3097)

In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [41]:
model = Sequential()
model.add(Embedding(3097, 100, input_length = 30))
model.add(LSTM(150))
model.add(Dense(3097, activation = 'softmax'))

In [42]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [43]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 30, 100)           309700    
                                                                 
 lstm_2 (LSTM)               (None, 150)               150600    
                                                                 
 dense_2 (Dense)             (None, 3097)              467647    
                                                                 
Total params: 927947 (3.54 MB)
Trainable params: 927947 (3.54 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [45]:
model.fit(X,encodedInput, epochs = 50)

Epoch 1/50
381/381 [==============================] - 28s 74ms/step - loss: 6.0203 - accuracy: 0.0628
Epoch 2/50
381/381 [==============================] - 28s 73ms/step - loss: 5.7237 - accuracy: 0.0770
Epoch 3/50
381/381 [==============================] - 27s 71ms/step - loss: 5.4272 - accuracy: 0.0939
Epoch 4/50
381/381 [==============================] - 28s 74ms/step - loss: 5.1279 - accuracy: 0.1059
Epoch 5/50
381/381 [==============================] - 28s 73ms/step - loss: 4.8344 - accuracy: 0.1216
Epoch 6/50
381/381 [==============================] - 27s 72ms/step - loss: 4.5466 - accuracy: 0.1415
Epoch 7/50
381/381 [==============================] - 27s 71ms/step - loss: 4.2557 - accuracy: 0.1739
Epoch 8/50
381/381 [==============================] - 27s 70ms/step - loss: 3.9792 - accuracy: 0.2064
Epoch 9/50
381/381 [==============================] - 27s 71ms/step - loss: 3.7009 - accuracy: 0.2554
Epoch 10/50
381/381 [==============================] - 35s 93ms/step - loss: 3.433

In [47]:
text = 'hello'
token = tokenizer.texts_to_sequences([text])[0]
token = pad_sequences([token], maxlen = 30, padding = 'pre')
model.predict(token)

1/1 [==============================] - 1s 544ms/step


array([[5.1255988e-10, 3.2514757e-01, 5.2520591e-01, ..., 2.9364822e-09,
        7.8038814e-10, 8.3293450e-12]], dtype=float32)

In [48]:
import numpy as np

In [49]:
index = np.argmax(model.predict(token))

1/1 [==============================] - 0s 41ms/step


In [50]:
index

2

In [51]:
for word, ind in tokenizer.word_index.items():
  if ind == index:
    print(word)

to


In [52]:
def predictor(string : str) -> str:
  token = tokenizer.texts_to_sequences([string])[0]
  token = pad_sequences([token], maxlen = 30, padding = 'pre')
  index = np.argmax(model.predict(token))
  for word, ind in tokenizer.word_index.items():
    if ind == index:
      print(word)

In [118]:
predictor('i don\'t like this new chinese place. I should\'ve just gone back my term out')

1/1 [==============================] - 0s 29ms/step
it


In [119]:
!pip install pyyaml h5py

In [120]:
import os

import tensorflow as tf
from tensorflow import keras

print(tf.version.VERSION)

2.15.0


In [121]:
model.save('wordPredictor.keras')

In [122]:
new_model = tf.keras.models.load_model('wordPredictor.keras')

# Show the model architecture
new_model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 30, 100)           309700    
                                                                 
 lstm_2 (LSTM)               (None, 150)               150600    
                                                                 
 dense_2 (Dense)             (None, 3097)              467647    
                                                                 
Total params: 927947 (3.54 MB)
Trainable params: 927947 (3.54 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [123]:
def predictor(string : str) -> str:
  token = tokenizer.texts_to_sequences([string])[0]
  token = pad_sequences([token], maxlen = 30, padding = 'pre')
  index = np.argmax(new_model.predict(token))
  for word, ind in tokenizer.word_index.items():
    if ind == index:
      print(word)

In [125]:
predictor('hello to')

1/1 [==============================] - 0s 31ms/step
hear
